### ISSUE TITLE
Invalid XML - Edgeworth_Princeton_C1256_undated_01.xml

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#11]
https://github.com/Maria-Edgeworth-Letters-Project/me-tei/blob/main/Encoded%20Letters/Edgeworth_Princeton_C1256_undated_01.xml

This letter does not validate in Oxygen. It needs:
1. '&' to be represented as `&amp;` in the letter (ampersands are reserved characters in XML)
2. An actual date to be inputted on line 231

Check the XML in Oxygen following edits to see if it validates.

**Comment by elizawilcox** [comment]
I fixed this and the only validation issue now showing is the keyword scheme issue.

**Comment by mlhale7** [comment]
Thanks @elizawilcox for fixing the ampersand issues. Note that the `dateline` actually needed to be removed altogether since the letter has no date (I didn't realize this when writing up this issue, so apologies for any confusion). I've made the additional changes and committed, so I'll resolve this issue.
