### ISSUE TITLE
Double check for typos

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#13]
https://github.com/Maria-Edgeworth-Letters-Project/me-tei/blob/f6d6d3df8c94df93496fea6a2cbdd08243d487fd/Encoded%20Letters/Edgeworth_Harvard_604760_1826-03.xml#L279

@elizawilcox - can you take a look at this letter and ensure that "honer" is not "honor"? Please also check for "'s" on Edgeworths family.

**Comment by elizawilcox** [comment]
This appears to be in line with the approved TXT file -- the "s" and the "honer"

**Comment by mlhale7** [comment]
@elizawilcox - would you mind taking a second look at the scanned letter itself? @hilaryhavens - is it appropriate to second guess the approved txt transcript in cases like this? I assumed that this was sort of built into the second pass on the text during encoding.

**Comment by hilaryhavens** [comment]
@mlhale7 I checked the scan, and there is, indeed, a typo.  However, we should be encoding the misspellings with <choice>, so I added that in, and I think it should work now.  Thank you for catching this!

**Comment by mlhale7** [comment]
@hilaryhavens - thank you for taking the time to check it. I really appreciate it. I'll go ahead and resolve this.

**Comment by hilaryhavens** [comment]
[like]  Havens, Hilary reacted to your message:
________________________________
