### ISSUE TITLE
Missing end tags </persName>

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#15]
The following XML records are invalid due to a missing closing persName element. Please add </persName> and ensure that the XML validates in Oxygen before committing. Comment on this issue when work is complete.

- Edgeworth_Beinecke_330_1817_02_16
- Edgeworth_Bodleian_696_1819_03_30
- Edgeworth_NLS_23130_1819_07_20

No XSLT can be run across the corpus if any files are invalid.

**Comment by elizawilcox** [comment]
All three letters have been fixed of all issues except for the keyword scheme error -- I believe that's supposed to be fixed by XSLT, but if not, let me know and I'll fix!

**Comment by mlhale7** [comment]
Thanks @elizawilcox for these changes. Sharing this just for knowledge purposes - I appreciate you clearly stating what's been updated. It's impossible to run XSLT on invalid XML. In order for me to run the XSLT, I have to manually remove the scheme error. All three XML files are now valid, so I'm closing this.
