### ISSUE TITLE
Error: "Content is not allowed in trailing section."

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#16]
The following XML records are invalid due to content "in the trailing section." It looks like someone was very conscientious about saving frequently and unfortunately added a trailing "s" to documents after `</TEI>` Comment on this issue when this work is complete and I'll review and close the issue.

- Edgeworth_Beinecke_330_1840_01_09
- Edgeworth_Bodleian_696_1819_04_letter01
- Edgeworth_Geneve_33_2_1809_08_22
- Edgeworth_Geneve_33_2_1811_06_30
- Edgeworth_Princeton_1834_07

Note that a single invalid XML document makes it impossible for me to run XSLT across the corpus of letters.

**Comment by mlhale7** [comment]
Edgeworth_Beinecke_330_1840_01_09.xml was completed as an example.

**Comment by krame21** [comment]
all of these now validate:
Edgeworth_Beinecke_330_1840_01_09
Edgeworth_Bodleian_696_1819_04_letter01
Edgeworth_Geneve_33_2_1809_08_22
Edgeworth_Geneve_33_2_1811_06_30
Edgeworth_Princeton_1834_07

**Comment by mlhale7** [comment]
@krame21 - thank you for looking these over and making edits. I really appreciate it. I removed `<textClass>` for a couple that still needed this. These are good to go now.
