### ISSUE TITLE
Letters outside the Encoded Letters folder

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#17]
The following letters were committed outside of the "Encoded Letters" folder:

- Edgeworth_Beinecke_330_1791_08_31.xml
- Edgeworth_Beinecke_330_1836.xml
- Edgeworth_Morgan_157752.xml
- Edgeworth_NLS_23130_1822_02_23.xml

Please move them to the correct folder and commit the changes.

**Comment by elizawilcox** [comment]
Moved and fixed!

**Comment by mlhale7** [comment]
Thanks @elizawilcox
