### ISSUE TITLE
Edits for letters

### ISSUE THREAD

**Issue by elizawilcox** [Maria-Edgeworth-Letters-Project/me-tei#18]
@aelagrand here are my edits for your letters -- I mistyped earlier when I said this would be a "pull request." I got my labels mixed up --it's an "issue ticket" we use to note issues in letters and assign people to fix them.

1844-02
- Line 25, add in the date between the <date></date> tag
- Lines 60-65 — format the “to” section the way it originally is formatted in the template — the way Edgeworth is formatted in the template needs to be changed, and we need to use the format <persName ref=“./Personography.xml#BentR1”> if we want it to actually pick up the xml:id from the Personography; same thing with the <date> tag here — add in the actual date in between
- Lines 95-99 — we haven’t been using the revision descriptions yet because I believe the idea was to use those for bigger changes — so if we went back in a year from now and changed how we’re tagging names or places, for example — but check with Meredith to see if that’s still what we’re doing/how <revisionDesc> should be treated; we’re not doing any xml:id’s for individual editors, so if we keep this, there isn’t an an xml:id (to my knowledge) for the who attribute
- Line 122 - I believe this work is Norton’s A Translation of the Gospels, so you should be able to tag it
- Lines 128-132 should be in the <closer> tag since they close the letter

Edgeworth_Princeton_1838-01-_page001
- Drop the “page001” from the title of the letter when saving — so it should read “Edgeworth_Princeton_1838-01.xml”
- Line 25, add in the date between the <date></date> tag
- Line 41 - drop “page001” from the <idno> tag
- Line 62 - add in date between <date> tag
- Lines 89-91 - same <revisionDesc> comments as above; double check with Meredith

Edgeworth_Princeton_1834-06
- I think this one should be separated — Princeton_1834_06_page01 is a different letter from Princeton_1834_06_page001 even though it copies from page001. I would say page001 needs to be a clean copy of Richard Bentley’s original letter to Maria Edgeworth and then the copy and answer (in page01) needs to be a separate letter altogether. I would advise double-checking with one of the core editors, like Hilary or Susan, or Meredith to make sure this is appropriate. 
- If solely encoding for the 001 letter, change appropriate information in the header to correspond
- Line 25, add in the date between the <date></date> tag
- Line 62 - add in date between <date> tag
- Lines 89-91 - same <revisionDesc> comments as above; double check with Meredith
- If solely encoding for the 001 letter, cut lines 134-170 and put into a separate encoded letter file
- Line 131-133, move to <closer> tag

**Comment by aelagrand** [comment]
@elizawilcox Thank you so much for your help and feedback in reviewing these letters!

Writing to confirm that I have applied the edits you noted for letters 1844-02 and 1838-01. I have also reached out to Dr. Egenolf to ask about 1834-06 to see whether or not to encode the two separately or together. Based on the response, I will go back and review 1834-06 and encode accordingly (while also applying your edits).
