### ISSUE TITLE
Edits for letters (Lindsey)

### ISSUE THREAD

**Issue by elizawilcox** [Maria-Edgeworth-Letters-Project/me-tei#19]
Edgeworth_Princeton_1800-01

1. Lines 11 and 22 - we’re not using xml:id’s to identify editors/transcribers, so you’ll want to remove your name from the ref attribute (ref=“Lindsey Jones”) and instead wrap your name in <persName> tags (<persName>Lindsey Jones</persName>
2. Line 30 - be sure to add the date in text field so that it will be visible to users, not just encoded in the tags
3. Lines 38-40 - be sure to include the JPG filenames associated with each letter
4. Line 65 — add the IDNO, which is the file title without any extensions — so for this one it would be Edgeworth_Princeton_1800-01
5. Line 78 — if the correct Johnson has been identified, add in the taxonomy tags here the same way they’re added in the letter proper
6. Lines 115-129 - I’m not sure we’re using <revisionDesc> this way — I believe we intended to use it for when major updates were made, but I could be wrong and you should check with Hilary or Meredith
7. Line 136 — this is where your first page break identifier should go rather than line 147, if the date and salutation are on the same page as the letter itself
8. Line 154 - missing a / in the ref tag, should be ref=“./Placeograophy.xml#Bristol_ENK”>
9. Line 162 - missing a / in the ref tag, should be ref=“./Placeograophy.xml#Dublin_IE”>

Edgeworth_Princeton_1834-1

1. Lines 11 and 22 - we’re not using xml:id’s to identify editors/transcribers, so you’ll want to remove your name from the ref attribute (ref=“Lindsey Jones”) and instead wrap your name in <persName> tags (<persName>Lindsey Jones</persName>
2. Line 29 - be sure to add the date in text field so that it will be visible to users, not just encoded in the tags
3. Lines 38-40 - be sure to include the JPG filenames associated with each letter
4. I believe R. Bentley is Richard Bentley — confirm with an editor and then make sure to encode the taxonomy at line 79 the same way you would in the letter
5. Also at line 79, encode for place with Edgeworthstown
6. Lines 116-124 - I’m not sure we’re using <revisionDesc> this way — I believe we intended to use it for when major updates were made, but I could be wrong and you should check with Hilary or Meredith
7. Line 131 — this is where your first page break identifier should go rather than line 142, if the date and salutation are on the same page as the letter itself
8. Line 135 - the formatting here is set up a bit differently, but the ref works the same — so it should be ref=“./Placeography.xml#Edgeworthstown_IE”> and if Edgeworthstown is indicated on the letter, it should be in the text field as well
9. Line 138 and line 143 — possible repetition of Sir
10. Line 149 - missing / for Place, should read <placeName ref=“./Placeography.xml#1-North-Audley-Street_ENK”>
11. Line 164 - I don’t believe we’ve been correct Obedt to Obedient, but double-check with Hilary and Meredith
12. Line 168 - I think that pb should be in the closer tag unless it’s not allowed there

**Comment by LindseyLJ** [comment]
I have made those changes and edits! @elizawilcox @mlhale7

**Comment by mlhale7** [comment]
@LindseyLJ - thanks for your work. I took a look today and have the following comments:

1. I think you can remove `revisionDesc`. In terms of consistency, we have not used this to date so it wouldn't be standard to start adding it now. In my opinion, tracking changes via GitHub is sufficient. I think these changes are mostly useful for an internal project audience rather than an external user audience. What you have done is not wrong, it just isn't something we've done in the project.
```      <revisionDesc>
         <change when="2023-10-15" who="Lindsey Jones">
            Created XML document.
         </change>
         <change when="2023-10-22" who="Lindsey Jones">
            Updated TEI to conform to MELP standards.
         </change>
         <change when="2021-01-01" who="Id_who">
            <!--Brief description of what you did here.-->
         </change>
      </revisionDesc>```
2. It looks like you have the wrong code for Helen in Edgeworth_Princeton_1834-1? The xml:id is currently Pract1 but should be Helen1.

@elizawilcox - Let us know if you noticed any other changes that still need to be addressed. If not, I'll close out this issue by the end of the week. @LindseyLJ - do also feel free to question any suggestions shared.

**Comment by LindseyLJ** [comment]
@mlhale7 Made those changes. Thanks!

**Comment by elizawilcox** [comment]
All looks good! I'm closing this out.
