### ISSUE TITLE
Filenaming

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#20]
@aelagrand - thanks for all of your work. I noticed looking briefly at the commit statements that some of the filenames include page numbers. For instance - Edgeworth_Princeton_1834-06_page001.xml We should just have Edgeworth_Princeton_1834-06.xml as the filename for the letter as a whole (even if it is just one page). Can you update the filename? I'll also note that we should remind everyone of this at our next meeting.

**Comment by aelagrand** [comment]
Hi @mlhale7 Thank you so much for flagging this. I think I had started with the correct file name of "Edgeworth_Princeton_1834-06" but had corrected it when I saw there were multiple letters with this ID. In the metadata spreadsheet, it comes up for two separate letters, so I think I thought that duplicates like this warranted the inclusion of "page001". Could we talk through this at our next meeting? That being said, I'll be sure to correct these in the meantime (sometime this weekend). Thank you!

**Comment by mlhale7** [comment]
@aelagrand - Thanks for this explanation. Yes, we don't want two letters with the same file name. I don't think adding page information is the way to distinguish one from another, but we do need to keep them distinct. We should all talk when we next meet. Don't bother correcting until we talk (as we may not be able to tell one apart from the other)

**Comment by aelagrand** [comment]
@mlhale7 Wonderful, thank you. I did already correct the file name, but I noticed that the two letters (1834-6_page01 and 1834-06_page001) included an original letter and its letter copy. Not sure if this affects anything, but I do remember that we were to leave the copies alone for now, so I didn't touch the copy. As of now, the file "Edgeworth_Princeton_1834-06" is encoded with the original.

**Comment by mlhale7** [comment]
@aelagrand - I'm going to close this issue with the intent of opening a broader issue eventually focused on copies.
