### ISSUE TITLE
Unknown dates

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#23]
Letters with no known date (no year, month, or day at all) have placeholder text in them for validation purposes in the template (1111-01-01).These and the entire date element need to be removed entirely from the XML as they list an inaccurate date. The removal will make the files both valid and accurate. The affected XML files include:

- Edgeworth_Beinecke_330_unknown_01
- Edgeworth_Beinecke_330_unknown_03
- Edgeworth_Beinecke_330_unknown_04
- Edgeworth_Geneve_33_2_unknown_04
- Edgeworth_Harvard_604762_unknown
- Edgeworth_Princeton_C0962_undated-01
- Edgeworth_Princeton_C0962_undated-02
- Edgeworth_Princeton_C0962_undated-03
- Edgeworth_Princeton_C0962_undated-04
- Edgeworth_Princeton_C1256_undated_01
- Edgeworth_Princeton_C1644_unknown_02
- Edgeworth_Princeton_C1664_undated-01

**Comment by mlhale7** [comment]
@elizawilcox Edgeworth_Harvard_604762_unknown seems to have a known date even though it's filename suggests otherwise. I'm inclined to keep the date element and maybe rename the file? Is this appropriate?

**Comment by mlhale7** [comment]
@aelagrand - thanks for your comments in XML on this exact issue. Sorry I missed them. Feel free to email me if you have questions.

**Comment by mlhale7** [comment]
@elizawilcox - looking at the file in our Drive (https://drive.google.com/file/d/1eV-rmRYtccDady3VHJoEVjf6bmcUrhT6/view?usp=sharing), the letter does clearly have a date. I'm going to rename this file and open a PR today. Please comment before this PR is merged if you think otherwise.

**Comment by aelagrand** [comment]
@mlhale7 No worries! Thank you for this direction. I will be sure to fix my undated letters and adhere to this going forward.

**Comment by mlhale7** [comment]
@aelagrand - I just saw your recent commits on undated letters. Note that I already addressed the issues in my PR so there's no need for you to do the same work. Once the PR is merged this will become apparent. Since we both were touching the same files, we may potentially have a merge conflict.

**Comment by aelagrand** [comment]
@mlhale7 So sorry! I was trying to address the notifications in the order I received them in my inbox, so I must have jumped the gun to fix them. I will be sure to read all GitHub notifications going forward to avoid this in the future.
