### ISSUE TITLE
Uncertain tag - ChamR1

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#25]
https://github.com/Maria-Edgeworth-Letters-Project/me-tei/blob/723987c493b2b5a23b23a448bd2b5660d8e26498/Encoded%20Letters/Edgeworth_Princeton_C1664_undated-01.xml#L149

@aelagrand - did we address this uncertain tag in our recent RA meeting or is the comment on this line still a question? If you are uncertain about referencing an individual in the taxonomy, the safest thing to do is to leave off a xml:id (though do ask the editors etc. and exhaust possibilities). We'd rather not identify a specific person if it causes us to potentially incorrectly identify someone. If this has been addressed, feel free to remove the comment in the XML (we wouldn't want this making it through to public users later). Otherwise we can have a discussion within this open issue on the identification. Emailing or commenting on the taxonomy terms sheet also works, but I opened this in GitHub since I had questions about the comment inclusion within the XML.

I'll close this issue when we have removed the uncertainty comment in the committed XML / figured out if we can assign a xml:id

**Comment by aelagrand** [comment]
@mlhale7 Thank you for flagging this. I did not bring it up at our recent meeting, but I am including it in a list of questions that I hope to share with editors soon (with other questions as well). I will report back when I have an answer and/or when I have fixed it.

**Comment by mlhale7** [comment]
@aelagrand - I've just closed the PR. Yes, do go ahead and remove the ID. Make sure to pull down changes first before editing the file.

**Comment by aelagrand** [comment]
@mlhale7 Writing back to confirm that I have removed the ID for Chambers and have recommitted the file!

**Comment by mlhale7** [comment]
@aelagrand - thanks! I'll close this out.
