### ISSUE TITLE
Unclear tag not around text

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#28]
https://github.com/Maria-Edgeworth-Letters-Project/me-tei/blob/f0d03985e8655302c90ca2e5c44d289e336652e8/Encoded%20Letters/Edgeworth_%20Princeton_1821-06.xml#L205C45-L205C59

@LindseyLJ  - `<unclear></unclear>` did not have any text within it when I processed the XML for the two PRs. Because of this, only `</unclear>` has been retained in the XML. Please update after the PRs have been closed with the text that should be found within. I'm assuming it should be `<unclear>/6</unclear>` though maybe it's the 12?

**Comment by LindseyLJ** [comment]
Corrected both of these instances!
