### ISSUE TITLE
Missing institution information

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#29]
While reviewing XML for the recent PRs, I came across a few records without the institutional information for the scans filled out. I'll list the records below noting the initial editor in parentheses. I'd ask that you fix the letter you initially committed and comment back on this issue when the work is complete.

- Edgeworth_NLS_23130_1822_04_24.xml (Eliza Alexander): see lines 39-43
- Edgeworth_Morgan_1828_02_08 (Autumn Hall - would someone else by willing to take this one on?): see lines 45-47

**Comment by mlhale7** [comment]
@elizawilcox - would you mind updating the NLS letter that you coded initially?

**Comment by elizawilcox** [comment]
@mlhale7 done! Thanks for the reminder, sorry this fell through my end of semester task list.

**Comment by mlhale7** [comment]
@elizawilcox - thank you! I've been going through a New Year's cleaning for Edgeworth :)
