### ISSUE TITLE
name element used in dateline instead of placeName

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#30]
@krame21 noticed that our TEI template still has a convention that we don't use in `dateline`. Rather than using `placeName`, we've used `name` with @type value of "place." This should be replaced with `placeName` in the template and across the existing XML. Note that xml:id values also have not been included for these placeNames and that this will be difficult to address programmatically. Here's an existing example:

```
            <opener>
               <dateline>
                  <name type="place" ref="Id_where"/>Black Castle
                  <date when="1836-12-03"/>Dec 3<hi rend="superscript">d</hi>. 1836</dateline>
               <salute>
                  <persName ref="./Personography.xml#WilsL1">My Dear Lestock</persName>
               </salute>
            </opener>
```
And here's what these lines should look like going forward:
```
            <opener>
               <dateline>
                  <placeName ref="./Placeography.xml#Black-Castle_IE">Black Castle</placeName>
                  <date when="1836-12-03"/>Dec 3<hi rend="superscript">d</hi>. 1836</dateline>
               <salute>
                  <persName ref="./Personography.xml#WilsL1">My Dear Lestock</persName>
               </salute>
            </opener>
```
Another issue is that it doesn't look like encoders have standardly closed the `name` element.

**Comment by mlhale7** [comment]
I've change all the name[@type="place"] values to `placeName`. @krame21 - can you take a look at two things:
1. update the @ref value from "Id_where" to the appropriate value in the taxonomy (it's possible not all places are in the taxonomy, so there may also be extra work there)
2. Check and see if all the `<placeName>` elements have a closing '</placeName>'

**Comment by krame21** [comment]
@mlhale7 I just saw this and I will start working on it as soon as I'm finished with these abbr tags :)

**Comment by mlhale7** [comment]
@krame21 - this may be something I can do relatively easily with a simple find and replace. I don't think we want name[@type="place"] anywhere in our TEI. I'll comment back if I complete this. I'll definitely be going ahead and updating it in the template.

**Comment by mlhale7** [comment]
@krame21 Still, please do check on the id_where issue mentioned. That's something I can't do without looking at them directly.

**Comment by mlhale7** [comment]
@krame21 - I did not find any instances of 'name type="place"' in our XML files. I have updated the template.

**Comment by krame21** [comment]
I have reviewed all instances of "id_where" and have replaced.

**Comment by krame21** [comment]
I have reviewed all instances of "id_where" and have replaced.
