### ISSUE TITLE
Encoding dates with no day

### ISSUE THREAD

**Issue by aelagrand** [Maria-Edgeworth-Letters-Project/me-tei#32]
@mlhale7 I have a couple of letters that have years and months, but no specific day. How should I encode that in the TEI?

It was suggested to put "00" or "xx", but neither of those would validate, so as of now, I have just placed "01". I did notice that taking out the date portion and just having the year and month validates, but I wanted to check before making that change. 

The letters in question are below:
Edgeworth_Princeton_1811-04
Edgeworth_Princeton_1838-10

Thank you in advance!

**Comment by mlhale7** [comment]
@aelagrand - thanks for opening this issue. When we encountered very unknown dates, we completely removed the machine readable date. Here, it's possible to actually just enter the information you know and leave off the remaining information. So for Edgeworth_Princeton_1811-04, you can enter:
```<date when="1811-04">```
This validates fine on my end, but let me know if you encounter any issues and I'll take another look.

**Comment by aelagrand** [comment]
@mlhale7 Wonderful! That validates on my end. I have gone ahead and updated Edgeworth_Princeton_1811-04 and Edgeworth_Princeton_1838-10 accordingly. Thank you!
