### ISSUE TITLE
Add note on spelling choices

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#34]
From December 2023 minutes:

- Add a “Note on the Text” to the template that appears in the text and not just as a comment:

```<!--Where Edgeworth uses nonstandard spelling and hyphenation of words, transcriber-coders should use TEI elements “choice," “sic," and “reg" to encode both Edgeworth’s spelling and the regular international standard of Oxford English spelling, following the first listed spelling in the Oxford English Dictionary.-->```

I'd propose that we do the following in the template and make this change across all letters:

```
        <editorialDecl>
            <p>Edgeworth’s spelling and punctuation are retained in transcription, except where a
               word is split at the end of a line and the beginning of the next in a manuscript. Where Edgeworth uses nonstandard 
               spelling and hyphenation of words, transcriber-coders 
               should use TEI elements “choice," “sic," and “reg" to encode both Edgeworth’s 
               spelling and the regular international standard of Oxford English spelling, 
               following the first listed spelling in the Oxford English Dictionary.The
               long s and ligatured forms are silently emended.</p>
         </editorialDecl>
```

**Comment by mlhale7** [comment]
We want to keep the commented text as a comment and amend the language in <p> as this is helpful to those encoding the letters.

**Comment by mlhale7** [comment]
I've opened a new branch and have changed the TEI template to include the following:

```
      <encodingDesc>
         <editorialDecl>
            <!--Where Edgeworth uses nonstandard spelling and hyphenation of words, transcriber-coders 
               should use TEI elements “choice," “sic," and “reg" to encode both Edgeworth’s 
               spelling and the regular international standard of Oxford English spelling, 
               following the first listed spelling in the Oxford English Dictionary. -->
            <p>Edgeworth’s spelling and punctuation are retained in transcription, including non-standard spelling, line breaks, and hyphenation of words. The long s and ligatured forms are silently emended.</p>
         </editorialDecl>
      </encodingDesc>
```
@hilaryhavens - let me know if this is not an accurate representation of the changes that need to be made across all letters.

**Comment by mlhale7** [comment]
Noting for future info that 5 records (out of our 219!!!) came back with errors while addressing this issue. The most common problem was simply adding closing tags.
![3-15-EdgeworthErrors](https://github.com/Maria-Edgeworth-Letters-Project/me-tei/assets/12545660/34b79a30-c53b-45f5-aeb7-24e0c2dd285c)

**Comment by hilaryhavens** [comment]
Thank you very much, Meredith!  The updated TEI template language (regarding non-standard spelling and grammar) looks great to me!
