### ISSUE TITLE
Add collective names to personography

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#35]
Research needs to be done to see how family names and other collective names might be added to the personography. This does not include corporate names for businesses, etc.

@elizawilcox suggested looking at `<orgName>` They came across this need in Edgeworth_Bodleian_696_10_29 with "the Hopes".

For reference, here's how a family entry is formatted according to Library of Congress standards - http://id.loc.gov/authorities/names/no2019175102 

For non-familial collectives, we could consider https://tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERSREL 

All should feel free to comment with suggestions. I'll share possibilities as I make them.

**Comment by mlhale7** [comment]
This article has ideas to consider in 3.3 and 3.4 - https://journals.openedition.org/jtei/1365#tocfrom2n4

**Comment by mlhale7** [comment]
Yellow Nineties has relationship info represented in triples - https://lincsproject.ca/docs/explore-data/project-datasets/yellow-nineties/yellow-nineties-application-profile#relationships

**Comment by elizawilcox** [comment]
I think the Early Modern England Map might be helpful for places where we have fewer identifying characteristics as well, like "sister of Mrs. Irwin" might look like this

```
<p>
  I talked to <person>
      <persName ref="./Personography.xml#IrwiX2">
          Mrs. Irwin's</persName>
      <persName ref="./Personography.xml#Anon1">
          <p>
              <note ref="./Personography.xml#IrwiX2">sister
              </note>
          </p>
      </persName>
  </person>  
</p>
```
This validates, but I'm not sure if it does what we want in corpora. I think the Yellow Nineties would be a good model for reciprocality as well, I just don't know how to do TTL to TEI. 

For the orgName, I played around and came up with this: 
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<p>
  I talked to the <person><persName><persName>ref="./Personography.xml#BailJ1"><persName ref="./Personography.xml#BailM1"></persName>
      <orgName ref="./Orgography.xml#BailX1">
      Baillies</orgName>
  </persName></persName>
</person>
</p>
```

It's messy, but what I was trying to retain was how to insert an orgName (collective) that would still pull up when searched collectively AND individually. We probably need something more streamlined than this, but that's what I've been working on/brainstorming, and it does validate in oXygen.

**Comment by mlhale7** [comment]
I think adding something like this below to the personography might work and be a bit more structured than the Maps of London example:

```
         <listRelation>
             <relation ref="https://dbpedia.org/ontology/parent" active="#EdgeR1" passive="#EdgeM1"/>
         </listRelation>
```

The issue would be figuring out all of the relationships we'd want to represent (here I just have parent).

**Comment by mlhale7** [comment]
Something like https://dbpedia.org/ontology/familyMember might be better for us to use than specifying specific family relationships (parent, sibling, etc.)

**Comment by elizawilcox** [comment]
That would definitely simplify things but still leave it open to more detail later down the road if that's wanted/warranted

**Comment by mlhale7** [comment]
We decided in our meeting we'll use https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-personGrp.html

`<relation>` doesn't meet the need of having a unique ID for the collective (and requires a lot of work).

**Comment by hilaryhavens** [comment]
That is correct - thank you very much, Meredith!
