### ISSUE TITLE
Image filename not included in TEI

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#38]
While Bryan demoed the MELP site today, he mentioned that there were many letters for which he could not find the image files to display in our Google Drive. For a subset of these the issue appears to be simply that the correct filename was not included in the TEI (image1.jpg or image2.jpg were left from the template). I've listed all of the errors of this type below.

Note that you'll want to be changing the filename error in several places. For these below with the image1.jpg issue, you may not need to change the name of the XML file itself (but you will for those listed on the spreadsheet in most cases). Otherwise you'll want to hit:

1. @ facs value within `<pb>`
2. filenames within `<editionStmt><respStmt><resp>` photos include:

- [x] Unable to locate image1.jpg for Edgeworth_Princeton_C1256_undated_01.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1836-11.xml
- [x] Unable to locate image2.jpg for Edgeworth_Princeton_1836-11.xml
- [x] Unable to locate image2.jpg for Edgeworth_Bodleian_696_1819_04_07.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1827-06.xml
- [x] Unable to locate image1.jpg for Edgeworth_ Princeton_1800-01.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1829-06.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1852-09_page001.xml
- [x] Unable to locate image2.jpg for Edgeworth_Princeton_1852-09_page001.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1829-11.xml
- [x] Unable to locate image2.jpg for Edgeworth_Princeton_1829-11.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1814-11.xml
- [x] Unable to locate image1.jpg for Edgeworth_Morgan_269586_1826_05_16.xml
- [x] Unable to locate image1.jpg for Edgeworth_ Princeton_1821-06.xml
- [x] Unable to locate image1.jpg for Edgeworth_NLS_23130_1822_02_23.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1825-12.xml
- [x] Unable to locate image2.jpg for Edgeworth_Bodleian_696_1819_04_17.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1823-08.xml
- [x] Unable to locate image1.jpg for Edgeworth_ Princeton_1816-01.xml
- [x] Unable to locate image1.jpg for Edgeworth_Princeton_1829-05.xml
- [x] Unable to locate image1.jpg for Edgeworth_ Princeton_1827-02.xml
- [x] Unable to locate image2.jpg for Edgeworth_Bodleian_696_1819_04_01.xml

Please include the correct file name for these and check off the box for each as you go.

**Comment by aelagrand** [comment]
Just a note to say that I started working on fixing the image file names, but for Edgeworth_Bodleian_696_1819_04_17, there is a validation error in the file that I cannot find. Not sure if it was there when I opened the file or if it came as a result of fixing the image file name. @mlhale7

**Comment by mlhale7** [comment]
@aelagrand - thanks for letting me know. There was a missing "/" to close out persName towards the start of the postscript. It took a bit to track down, so I can see why you couldn't find it.

**Comment by aelagrand** [comment]
@mlhale7 I'm glad to hear you were able to find the missing "/"! I had searched and searched and just couldn't find it. Additionally, I have finished my portion of the above files, but could not find "Edgeworth_ Princeton_1821-06.xml" in the encoded letters folder.

**Comment by elizawilcox** [comment]
@mlhale7 @hilaryhavens for Edgeworth_Princeton_1852-09, there doesn't seem to be any actual content done in these letters, and from what I can see, it's unclear who did these letters. I've went ahead and replaced the "image1" with "Edgeworth_Princeton_1852-09-001.jpg" so it doesn't return incorrectly but aside from that have added nothing.

**Comment by elizawilcox** [comment]
> @mlhale7 I'm glad to hear you were able to find the missing "/"! I had searched and searched and just couldn't find it. Additionally, I have finished my portion of the above files, but could not find "Edgeworth_ Princeton_1821-06.xml" in the encoded letters folder.

I think it's at the top and separate from the other Princeton files (not sure why) -- I can see it on my end. If you can't still, let me know, and I can take this one.

**Comment by aelagrand** [comment]
@elizawilcox Fantastic! Thank you. Not sure how I missed it, but just fixed it.

**Comment by mlhale7** [comment]
@aelagrand @hilaryhavens - I'm reviewing the list to see what issues are still outstanding. I'll comment with a full list of issues soon. First I wanted to mention that it looks like there may be an issue with referencing the same page twice in the same TEI file. I am trying to see what is wrong with Edgeworth_Princeton_1827_06_page01.jpg and the only thing I can think of is that there's an expectation that the same page wouldn't be referenced twice in the same letter? Do others have thoughts? Should I ask Bryan about this? Here's the link to the letter online - https://melp.dh.tamu.edu/letters/Edgeworth_Princeton_1827_06.xml/ I think the postscript might be the problem because of how the letter initially appears online.

**Comment by mlhale7** [comment]
@aelagrand @hilaryhavens @krame21 here are the errors that remain unresolved that are specifically mentioned on this issue:

- [ ]  Unable to locate image1.jpg for Edgeworth_Princeton_1836-11.xml
- [ ] Unable to locate image2.jpg for Edgeworth_Princeton_1836-11.xml

**Comment by hilaryhavens** [comment]
Hi Meredith, I looked at the code for Edgeworth_Princeton_1827_06.xml, and the second time page 1 was referenced, there was a dash instead of an underscore (<pb n="1" facs="Edgeworth_Princeton_1827-06_page01.jpg"/>).  I think that's the reason the page wasn't displaying.  I fixed that.

Edgeworth_Princeton_1823_08.xml is more puzzling, though.  One potential reason why Edgeworth_Princeton_1823_08.xml is weird is possibly because <pb n="1" facs="Edgeworth_Princeton_1823_08_page01.jpg"/>appears in the <address> field.  Another is because the page numbers are off.  Page 1 actually appears at the end of the letter instead of the beginning, so if Bryan is pulling the image files from the header and putting them in order, this could be causing difficulties.  Or, this could be another thing to bring up with Bryan.  Thank you for all of your great work!

**Comment by mlhale7** [comment]
@hilaryhavens - thank you for this. I believe you have addressed the issue for Edgeworth_Princeton_1827_06.xml, but I'll wait to update this ticket until I can see that it has worked in the interface.

For Edgeworth_Princeton_1823_08.xml, after looking closely at the scans, I do think page 1 is inaccurately put at the end of the letter in the `<address>` field. I have removed that from the TEI. For the second example I shared, it looks like the ordering has thrown things off, but it is caused by the number we gave the pages on drive (the addrLine info is on "page01"). I've updated the pages on the Drive and updated the TEI https://melp.dh.tamu.edu/letters/Edgeworth_Princeton_1823_08.xml/

I believe there are cases where we will actually need to put _page01.jpg at the end of the TEI though and that Bryan's code likely shouldn't assume pages always advance chronologically.

**Comment by hilaryhavens** [comment]
Thanks, @mlhale7 !  And thanks for making these corrections to Edgeworth_Princeton_1823_08.xml.  It should be okay - theoretically - to have a <pb> within <address> (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-address.html), so hopefully this works out.  Hopefully renumbering solves the problem this time, but yes, you are right - sometimes we need to return to page01 at the end of the letter (causing that page to appear twice) because the postscript is written on the first page (since she ran out of room).  Many thanks and see you tomorrow!

**Comment by mlhale7** [comment]
Just a fyi that it looks like our C1664 Princeton data folder still has a ton of letters with an extra space in the filename (for instance `Edgeworth_ Princeton_1852-09_page001`). The extra space is right before "Princeton." I'm going through and addressing these so that we can close this ticket.

**Comment by hilaryhavens** [comment]
Great - thank you, Meredith!
