### ISSUE TITLE
Edgeworth misspelled in citation field

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#40]
Maria Edgeworth's name is spelled as "Edegeworth, M." in the citation field on https://melp.dh.tamu.edu/letters I'm uncertain where we're pulling this information from, but from spot checking a few records it seems to be across all records? If someone has time to look into this, feel free to assign yourself to this ticket.

![EdgeworthCitationMisspelling](https://github.com/Maria-Edgeworth-Letters-Project/me-tei/assets/12545660/7ade31dd-b702-4250-8bcf-f976bbe7ff0f)

**Comment by hilaryhavens** [comment]
Hi Meredith, thanks for catching this!!!  I had a look at this, and I don't see the misspelling in the template.  I think this is part of the standard citation text that Bryan probably put together, so I am adding it to a new list of queries for Bryan (in the TEI / Database development folder): https://docs.google.com/document/d/1YqdznDkrZg-11jB6mvh4Dy3f0oNq1zActMIx9kgu0Zc/edit.

**Comment by mlhale7** [comment]
Issue opened here - https://github.com/bptarpley/wp_melp/issues/1

**Comment by mlhale7** [comment]
Bryan addressed this - thanks!
