### ISSUE TITLE
Image Errors (6/20)

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#43]
Bryan shared our remaining image errors after updating the site on 6/20. Please check each as you complete corrections. Some are due to the space issue in filenames (though it looks like the extra space is in the TEI).

- [x] Unable to locate Edgeworth_Beinecke_330_unknown01_page02.jpg for Edgeworth_Beinecke_330_unknown01.xml
- [x] Unable to locate Edgeworth_ Princeton_1833-10_page01.jpg for Edgeworth_Princeton_1833-10.xml
- [x] Unable to locate Edgeworth_ Princeton_1833-10_page02.jpg for Edgeworth_Princeton_1833-10.xml
- [x] Unable to locate Edgeworth_ Princeton_1833-10_page03.jpg for Edgeworth_Princeton_1833-10.xml
- [x] Unable to locate Edgeworth_ Princeton_1833-10_page04.jpg for Edgeworth_Princeton_1833-10.xml
- [x] Unable to locate image1.jpg for Edgeworth_Bodleian_696_1820_letter01.xml
- [x] Unable to locate image2.jpg for Edgeworth_Bodleian_696_1820_letter01.xml
- [x] Unable to locate Edgeworth_Huntington_FB1239_1817_06_xx_page04.jpg for Edgeworth_Huntington_FB1239_1810_06_xx.xml
- [x] Unable to locate Edgeworth_Bodlein_696_1818-10-29_page01.jpg for Edgeworth_Bodleian_696_1818_10_29.xml
- [x] Unable to locate Edgeworth_Bodleian_1819_04_08_page04.jpg for Edgeworth_Bodleian_696_1819_04_08.xml
- [x] Unable to locate Edgeworth_Princeton_1834_06_page001.jpg for Edgeworth_Princeton_1834-06_page001.xml
- [x] Unable to locate Edgeworth_Huntington_HM28617_1828_08_29_page01.jpg for Edgeworth_Huntington_HM28617_1828_08_29.xml
- [x] Unable to locate Edgeworth_Huntington_HM28617_1828_08_29_page02.jpg for Edgeworth_Huntington_HM28617_1828_08_29.xml
- [x] Unable to locate Edgeworth_Huntington_HM28617_1828_08_29_page03.jpg for Edgeworth_Huntington_HM28617_1828_08_29.xml
- [x] Unable to locate Edgeworth_Huntington_HM28617_1828_08_29_page04.jpg for Edgeworth_Huntington_HM28617_1828_08_29.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page01.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page02.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page0#.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page04.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page05.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page06.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page07.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Claremont_00583_1840_05_page08.jpg for Edgeworth_Claremont_00583_1841_05_31.xml
- [x] Unable to locate Edgeworth_Princeton_1827-02_page02.jpg for Edgeworth_Princeton_1827-02.xml
- [x] Unable to locate Edgeworth_Harvard_604742_unknown_page02.jpg, for Edgeworth_Harvard_604742_unknown.xml
- [x] Unable to locate Edgeworth_NLS_6931_1816_01_10_page02.jpg for Edgeworth_NLS_6931_1816_01_10.xml
- [x] Unable to locate Edgeworth_NLS_6931_1816_01_10_page03.jpg for Edgeworth_NLS_6931_1816_01_10.xml
- [x] Unable to locate Edgeworth_NLS_6931_1816_01_10_page04.jpg for Edgeworth_NLS_6931_1816_01_10.xml
- [x] Unable to locate Edgeworth_Beinecke_330_1840_01_09_page01.jpg for Edgeworth_Beinecke_330_1840_01_09.xml
- [x] Unable to locate Edgeworth_Bodleian_696_1819-04_XX_page01.jpg for Edgeworth_Bodleian_696_1819_04_XX.xml
- [x] Unable to locate Edgeworth_Bodleian_696_1819-04_XX_page02.jpg for Edgeworth_Bodleian_696_1819_04_XX.xml
- [x] Unable to locate Edgeworth_Bodleian_696_1819-04_XX_page03.jpg for Edgeworth_Bodleian_696_1819_04_XX.xml
- [x] Unable to locate Edgeworth_Princeton_1834-06_page003.jpg for Edgeworth_Princeton_1834_06_30.xml

**Comment by mlhale7** [comment]
@hilaryhavens - I don't see any files for Edgeworth_Huntington_HM28617_1828_08_29 on our Drive. It's possible I'm simply missing them, but I have looked a few times.

@krame21 - are you still working on reconciling the spaces in the Huntington files? Just wanted to check on the status of this.

**Comment by mlhale7** [comment]
@hilaryhavens - we're also missing files for Edgeworth_NLS_6931_1816_01_10. Only page 1 is on the Drive. I'm happy to do simple filename changes, but I think we need someone in charge of images to recapture missing pages according to standards.
![NLSImages](https://github.com/Maria-Edgeworth-Letters-Project/me-tei/assets/12545660/75c1fece-6c3d-48b3-9ee7-bce766cc46c1)

**Comment by hilaryhavens** [comment]
Hi Meredith, I will look for those missing Huntington and NLS images right now!

**Comment by hilaryhavens** [comment]
Hi Meredith,

The Huntington letter images were in the format: "Edgeworth_Huntington_XXXX_1828_08_29_page01.jpg."  I have replaced those Xs with "HM28617", so I think the images should appear the next time Bryan runs the WordPress update without any need to change the XML file.  Will work on NLS now.  Thanks!

**Comment by mlhale7** [comment]
@hilaryhavens - thank you for your eyes. I'll check those off!

**Comment by hilaryhavens** [comment]
[like]  Havens, Hilary reacted to your message:
________________________________

**Comment by hilaryhavens** [comment]
@mlhale7 Ok - I found the NLS ones.  The date for pages 2-4 was wrong and was listed as 1818 instead of 1816, i.e. Edgeworth_NLS_6931_1818_01_10_page03.jpg.  I have fixed those now, and we shouldn't need to change the XML.

In the future, I am happy to track these down to save you time.  Same goes for @aelagrand and @krame21 - if there is a missing image and you can't find it quickly, just tag me / let me know.

**Comment by krame21** [comment]
> @krame21 - are you still working on reconciling the spaces in the Huntington files? Just wanted to check on the status of this.

Yes I am getting started working on them now :)

**Comment by krame21** [comment]
> @hilaryhavens - I don't see any files for Edgeworth_Huntington_HM28617_1828_08_29 on our Drive. It's possible I'm simply missing them, but I have looked a few times.

@mlhale7 @hilaryhavens this is strange, and I'm not sure if I'm missing something with the spacing/spelling, but I even cut and paste the file name (Edgeworth_Huntington_HM28617_1828_08_29) into the jpeg file names to make sure that they match. They continue to not show up in searches of the drive. I tested another letter just to see if it was my connection, but no, all of the associated files with that name show up with other letters. Not sure how else to resolve this.
![Image 6-21-24 at 6 11 AM](https://github.com/Maria-Edgeworth-Letters-Project/me-tei/assets/92738906/15fb0fae-3934-4361-912b-9e65e1d7153e)

**Comment by krame21** [comment]
Well, my previous comment was asinine because Hilary resolved it! Can you tell I am catching up? I am not deleting this above comment though because I find it so strange that it's not showing up in the drive for me when I search it--or is it just google being finicky?

**Comment by mlhale7** [comment]
@krame21 - thanks for working on the Huntington spaces. I typically search as a last resort and browse through everything. It does take time, but then I can (typically) see if I'm missing a simple formatting change in the filename. I honestly don't know why not everything for a certain letter would be retrieved for a search in Drive.

**Comment by hilaryhavens** [comment]
@mlhale7 @krame21 I have issues with Drive searching too.  I think order / completeness matters when you are typing in the filename.  I try to search for parts of it, and sometimes that helps.  For me, the most effective thing is to go into a folder where I know (or am very sure) the files will be and sort by name.  Then I scroll down and look or use the CTRL-F find.  That helps, but yes, I agree that there are issues with Google Drive.

**Comment by krame21** [comment]
@mlhale7 @hilaryhavens all of the spaces in Huntington have now been corrected.

**Comment by krame21** [comment]
@mlhale7 @hilaryhavens with regard to google drive searching, I started selecting "title only" in my search results, and that is now pulling everything up in the drive--not sure if it's a solution for every situation, but it's working for this!

**Comment by krame21** [comment]
Unable to locate Edgeworth_Beinecke_330_1840_01_09_page01.jpg for Edgeworth_Beinecke_330_1840_01_09.xml
Unable to locate Edgeworth_Bodleian_696_1819-04_XX_page01.jpg for Edgeworth_Bodleian_696_1819_04_XX.xml
Unable to locate Edgeworth_Bodleian_696_1819-04_XX_page02.jpg for Edgeworth_Bodleian_696_1819_04_XX.xml
Unable to locate Edgeworth_Bodleian_696_1819-04_XX_page03.jpg for Edgeworth_Bodleian_696_1819_04_XX.xml
Unable to locate Edgeworth_Princeton_1834-06_page003.jpg for Edgeworth_Princeton_1834_06_30.xml

----Added these to the list & they are all resolved.
