### ISSUE TITLE
Records with missing <correspDesc>

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#5]
Add sender and receiver values for those that are missing them.

`<correspDesc>
                <correspAction type="sent">
                    <persName ref="./Personography.xml#EdgeR1">Richard Lovell Edgeworth</persName>
                </correspAction>
                <correspAction type="received">
                    <persName ref="./Personography.xml#DayX1">Mrs. Day</persName>
                </correspAction>
            </correspDesc>`

TEI Filenames:

- [ ] Edgeworth_Princeton_C1644_unknown_02.xml (added to file by Eliza on 12/7/22)

Keep adding letter filenames (or create a list elsewhere and link to this issue)

**Comment by elizawilcox** [comment]
Updating this with a list of other things in these letters that are different from the current TEI template

1. Edgeworth_Princeton_C1644_unknown_02.xml - missing the ʻ<bibl>ʻ statement in the most recent template

**Comment by krame21** [comment]
@mlhale7 @hilaryhavens  All files now have a <correspDesc> that also has a <persName> ID tagged. all "sent" and "received" sections of <correspAction> have been deleted if there is an unknown value.

**Comment by hilaryhavens** [comment]
Thank you, Jamie!!
