### ISSUE TITLE
Duplicate Letters

### ISSUE THREAD

**Issue by mlhale7** [Maria-Edgeworth-Letters-Project/me-tei#6]
In the encoded letters folder there is both "Unknown.xml" and "Edgeworth_NLS_936_1832_07_22.xml". It looks like they are the same letter and that one (likely "Unknown") can be deleted. Please confirm that this is the case and delete the least up to date letter.

**Comment by mlhale7** [comment]
Additionally, there are two letters with the identifier "Edgeworth_Morgan_157752". One is in the Encoded_Letters folder and one is at the top level of the me-tei repository. Please select the most up to date letter and remove the other (ensuring that it is placed within the Encoded_Letters folder).

**Comment by elizawilcox** [comment]
@mlhale7 yes, "Unknown.xml" is a copy (don't know how that got there) and "Edgeworth_NLS_936_1832_07_22.xml" is the most up to date. Will go delete "Unknown.xml" now.

**Comment by mlhale7** [comment]
@elizawilcox - thanks for this. I'll remind myself not to assign things to you this semester since your assistantship is not related. Apologies!

**Comment by elizawilcox** [comment]
@mlhale7 if it's small stuff like this (and letters I coded), I don't mind! I'm still working on stuff related to the journal article, too.
